### ISSUE TITLE
회원가입시 role에 특정값을 할당할지 null로 표기할지 의논이 필요합니다!

### ISSUE THREAD

**Issue by eotkd4791** [mostoriginaldudes/WhistleOn#26]
![스크린샷 2021-05-19 오후 5 54 50](https://user-images.githubusercontent.com/46208349/118784857-517dc180-b8cb-11eb-94fd-bbde5570f7d9.png)

회원가입시 무소속 선수로 시작하기 때문에 role 값을 null로 둘지, 아니면 특정한 값을 할당할지의 여부에 대한 상의가 필요합니다.

확인하시면 함께 얘기하시죠 :)

**Comment by sangwoo0727** [comment]
Role은 말씀하신거처럼 회원가입하는 시점에는 아무런 역할이 없고, 화면 단에서는 코드 로직적으로도 신경쓸 필요가 없습니다.
회원가입하는 화면에서는 Role을 고르는 부분이 없고, 있을 필요도 없으니깐요.
회원가입은 Role을 제외한 회원가입 로직에 필요한 데이터를 보내주시면 되고, Role은 회원가입하는 시점에 서버에서 임의로 None이라는 디폴트값으로 넣을 예정입니다~

노션 부분은 제가 수정해두겠습니다

**Comment by eotkd4791** [comment]
> Role은 말씀하신거처럼 회원가입하는 시점에는 아무런 역할이 없고, 화면 단에서는 코드 로직적으로도 신경쓸 필요가 없습니다.
> 회원가입하는 화면에서는 Role을 고르는 부분이 없고, 있을 필요도 없으니깐요.
> 회원가입은 Role을 제외한 회원가입 로직에 필요한 데이터를 보내주시면 되고, Role은 회원가입하는 시점에 서버에서 임의로 None이라는 디폴트값으로 넣을 예정입니다~
> 
> 노션 부분은 제가 수정해두겠습니다

완벽하게 이해하였습니다 ! 감사합니다 !!
